// Type definitions matching public/data/mlb/mlb_daily.json
// (Generated by exporters/mlb/daily_spreadsheet.py.)

export type ConvictionTier =
  | "Signal Elite"
  | "Strong Signal"
  | "Moderate Signal"
  | "Lean Signal"
  | "No Signal";

export type TabKey =
  | "todays_card"
  | "moneyline"
  | "run_line"
  | "totals"
  | "first_5"
  | "first_inning"
  | "team_totals"
  | "backtest";

export interface BetTab {
  title: string;
  projection_section_title?: string;
  backfill_section_title?: string;
  projection_columns: string[];
  backfill_columns: string[];
  projections: Record<string, unknown>[];
  backfill: Record<string, unknown>[];
}

export interface TodaysPlay {
  date?: string;
  matchup?: string;
  starting_pitchers?: string;
  bet_type?: string;
  pick?: string;
  model_prob?: number;
  fair_odds_dec?: number;
  market_odds_dec?: number;
  market_odds_american?: number;
  book?: string;
  edge_pct?: number;
  kelly_pct?: number;
  kelly_advice?: string;
  portfolio_scaled_from?: number;
}

export interface BacktestSummaryRow {
  scope: "OVERALL" | "BY TYPE" | "CLV" | "CLV BY TYPE";
  bet_type: string;
  bets: number;
  wins: number;
  losses: number;
  pushes: number;
  hit_rate: number;
  units_pl: number;
  roi_pct: number;
  brier?: number | null;
}

export interface DailyPLRow {
  date: string;
  daily_units: number;
  cumulative_units: number;
}

export interface MLBDailyData {
  generated_at: string;
  season: number;
  today: string;
  odds_source: string;
  odds_fetched_at: string | null;
  counts: {
    backfill_games: number;
    slate_games: number;
    priced_games: number;
  };
  tabs: Record<TabKey, BetTab>;
  odds: { fetched_at: string | null; source: string; games: unknown[] };
  backtest: {
    overall: {
      bets: number;
      wins: number;
      losses: number;
      pushes: number;
      hit_rate: number;
      units_pl: number;
      roi_pct: number;
      brier?: number | null;
    };
    summary_by_bet_type: BacktestSummaryRow[];
    daily_pl: DailyPLRow[];
    bets: Array<{
      date: string;
      matchup: string;
      bet_type: string;
      pick: string;
      model_prob: number;
      result: "WIN" | "LOSS" | "PUSH";
      units: number;
    }>;
  };
}

const DATA_URL = "/data/mlb/mlb_daily.json";

/** Fetch the daily payload. Server-side; called from a Server Component. */
export async function getDailyData(origin?: string): Promise<MLBDailyData | null> {
  const url = origin ? `${origin}${DATA_URL}` : DATA_URL;
  try {
    const res = await fetch(url, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as MLBDailyData;
  } catch {
    return null;
  }
}
