// Type definitions matching public/data/mlb/mlb_daily.json
// (Generated by exporters/mlb/daily_spreadsheet.py.)

export type KellyAdvice = "PASS" | "0.5u" | "1u" | "2u" | "3u";

export type TabKey =
  | "todays_card"
  | "moneyline"
  | "run_line"
  | "totals"
  | "first_5"
  | "first_inning"
  | "team_totals"
  | "backtest";

export interface BetTab {
  title: string;
  projection_section_title?: string;
  backfill_section_title?: string;
  projection_columns: string[];
  backfill_columns: string[];
  projections: Record<string, unknown>[];
  backfill: Record<string, unknown>[];
}

export interface BacktestSummaryRow {
  scope: "OVERALL" | "BY TYPE";
  bet_type: string;
  bets: number;
  wins: number;
  losses: number;
  pushes: number;
  hit_rate: number;
  units_pl: number;
  roi_pct: number;
}

export interface DailyPLRow {
  date: string;
  daily_units: number;
  cumulative_units: number;
}

export interface MLBDailyData {
  generated_at: string;
  season: number;
  today: string;
  odds_source: string;
  odds_fetched_at: string | null;
  counts: {
    backfill_games: number;
    slate_games: number;
    priced_games: number;
  };
  tabs: Record<TabKey, BetTab>;
  odds: {
    fetched_at: string | null;
    source: string;
    games: unknown[];
  };
  backtest: {
    overall: {
      bets: number;
      wins: number;
      losses: number;
      pushes: number;
      hit_rate: number;
      units_pl: number;
      roi_pct: number;
    };
    summary_by_bet_type: BacktestSummaryRow[];
    daily_pl: DailyPLRow[];
    bets: Array<{
      date: string;
      matchup: string;
      bet_type: string;
      pick: string;
      model_prob: number;
      result: "WIN" | "LOSS" | "PUSH";
      units: number;
    }>;
  };
}
